feat: move reporter from https://github.com/re-gor/porchmark-pretty-reporter
mutantcornholio/porchmark pull request #17
Opened 2021-05-05 09:11 UTC by alekzonder

Перетащил репортер в packages/porchmark-pretty-reporter

Если @re-gor будет против, можем выпилить и изменить у него

2021-05-05 09:15 UTC, mutantcornholio requested changes
1. Давай сначала узнаем, будет ли @re-gor против, а потом будем забирать код
2. Как насчёт скопировать код через `git subtree`, чтобы сохранить все коммиты и авторов, а потом сверху сделать работу по интеграции?

2021-05-05 09:38 UTC, alekzonder commented
Он в отпуске, узнаем недели через 3

2021-05-07 10:34 UTC, alekzonder commented
@mutantcornholio /ping

2021-05-07 11:28 UTC, mutantcornholio approved these changes
найс

2021-05-07 15:59 UTC, merged