compare sites with web page replay and lighthouse
mutantcornholio/porchmark pull request #3
Opened 2019-11-20 11:41 UTC by alekzonder

2019-11-30 19:04 UTC, mutantcornholio requested changes
Я начал вникать и вижу, что ты просто построил ещё один порчмарк рядом с изначальным, в другой файловой структуре, подходах и даже продублировал часть логики.
Я совершенно не понимаю, как это принять

2019-11-30 19:04 UTC, mutantcornholio commented on README.md
> +## `porchmark compare-releases --config <filefile>`
Давай конфиг для `porchmark` будет один общий, а не свой под каждый режим?

2019-11-30 19:04 UTC, mutantcornholio commented on README.md
> +  "urls": [ // ------------------------------- urls for compare
зачем хосты и урлы разделять?

2019-11-30 19:04 UTC, mutantcornholio commented on README.md
> +Config file identical with `compare-releases`
ну тем более)

2019-11-30 19:04 UTC, mutantcornholio commented on package.json
> +    "joi": "^14.3.1",
![Screen Shot 2019-11-30 at 18 38 02](https://user-images.githubusercontent.com/588262/69902574-93960900-13a0-11ea-92ec-aa54f788f597.png)

2019-11-30 19:04 UTC, mutantcornholio commented on package.json
> +    "watch": "ln -sf ../dist node_modules/@ && tsc --watch",
кажется, надо вот так: https://github.com/joonhocho/tscpaths/issues/4#issuecomment-470894967

2019-11-30 19:04 UTC, mutantcornholio commented on src/bin/porchmark.ts
> +import {createLogger} from "@/lib/logger";
Мешанина из разных кавычек бросается в глаза. Думаю, стоит после того, как эти PR вмёржим, завести какой-нибудь кодстайл сюда

2019-11-30 19:04 UTC, mutantcornholio commented on src/bin/porchmark.ts
> +if (!currentCommand.length) {
Если сделать команды отдельными файлами [как в veendor](https://github.com/mutantcornholio/veendor/tree/master/src/bin), то такое не нужно будет

2019-11-30 19:04 UTC, mutantcornholio commented on src/classes/Api/index.ts
> +        this._logger = logger;
Если заводишь отдельный логгер, сделай его глобальным. Когда будешь разносить этот модуль на кучу файлов, понадобится)
Вот так
https://github.com/mutantcornholio/veendor/blob/31078e0ae68a67b494d7f38c49657927d99254b6/src/lib/util/logger.ts#L6
https://github.com/mutantcornholio/veendor/blob/31078e0ae68a67b494d7f38c49657927d99254b6/src/bin/veendor-calc.ts#L22

2019-11-30 19:04 UTC, mutantcornholio commented on src/classes/Api/index.ts
> +    public static async createWorkDir(logger: Logger, workDir: string): Promise<void> {
Этому явно не в общем классе место

2019-11-30 19:04 UTC, mutantcornholio commented on src/classes/Api/index.ts
> +    }
методы для вызова статичных методов, лишь бы прокидывать логгер? ват?

2019-11-30 19:04 UTC, mutantcornholio commented on src/classes/Api/index.ts
> +    public async recordWpr(
Давай всё про запись wpr в отдельный модуль

2019-11-30 19:04 UTC, mutantcornholio commented on src/classes/Api/index.ts
> +    }
Я вижу три одинаковых функции. Сделай одну универсальную, зачем такое апи с `recordXForX`?

2019-11-30 19:04 UTC, mutantcornholio commented on src/classes/Api/index.ts
> +        );
Может, разделим `options` и `dataProcessor` в таком случае?
`workerFarm#startWorking` например, принимает их отдельно

2019-12-02 03:37 UTC, alekzonder commented on README.md
> +## `porchmark compare-releases --config <filefile>`
он и так общий, просто временно оставил оригинальную команду как есть

сначала не очень понятно было как все это интегрировать в workerFarm, потому что там гораздо больше телодвижений подними WPR дождись, останови и прочее, поэтому начал делать отдельно 

конфиг в принципе общий, там куча опций, которые в идеале нужно сделать опциями команд, сделал только `--config` потому что так было быстрее, можно вытащить все в опции тогда можно указывать конфиг и потом переопределять какие-то опции через аргументы

```
porchmark compare-releases --config ./some-config.js --options.cacheEnabled false
```

2019-12-02 03:44 UTC, alekzonder commented on README.md
> +  "urls": [ // ------------------------------- urls for compare
WPR по файлам разделяются и по урлам создаются директории, получается все достаточно логично

```
./workDir
  main/
    prestable-0.wprgo
    ...
    prestable-1.wprgo
    production-0.wprgo
    production-1.wprgo
  product/
    ...
```

аналогично с метриками, логами и другими файлами

логика была такая, есть несколько урлов, которые нужно сравнивать, мы их описываем в urls и даем уникальный name

потом описываем пару хостов и запускаем

можно конечно переделать на urls, тогда будет общее вложенная структура конфига, но по сути внутри происходит это преобразование в comparations и внутри работаем уже с ним

```
...
"comparations": [
    {
      "name": "product",
      "config": {
        "workDir": "/workd-dir/product",
        "headless": true,
        "sites": [
          {
            "name": "market1",
            "url": "https://m.market.yandex.ru/product--smartfon-apple-iphone-7-32gb/14206636",
            "mobile": true
          },
          {
            "name": "market2",
            "url": "https://m.market.yandex.ru/product--smartfon-apple-iphone-7-32gb/14206636",
            "mobile": true
          }
        ],
        "useWpr": true,
        "silent": false,
        "iterations": 3,
        "cacheEnabled": true,
        "javascriptEnabled": true,
        "imagesEnabled": true,
        "cssFilesEnabled": true
      }
    }
  ]
```

2019-12-02 04:00 UTC, alekzonder commented on package.json
> +    "joi": "^14.3.1",
исправил

2019-12-02 04:06 UTC, alekzonder commented on package.json
> +    "watch": "ln -sf ../dist node_modules/@ && tsc --watch",
исправил

2019-12-02 04:07 UTC, alekzonder commented on src/bin/porchmark.ts
> +import {createLogger} from "@/lib/logger";
да нужно будет tslint добавить

2019-12-02 04:28 UTC, alekzonder commented on src/classes/Api/index.ts
> +    }
где-то был TODO коммент `fix this shit`, но протерялся видимо
да это криво

2019-12-02 06:59 UTC, mutantcornholio commented on README.md
> +## `porchmark compare-releases --config <filefile>`
> он и так общий, просто временно оставил оригинальную команду как есть

Прости, но это звучит как «он общий, просто нет» =)
Форматы кофигов совершенно разные

2019-12-02 07:01 UTC, mutantcornholio commented on README.md
> +  "urls": [ // ------------------------------- urls for compare
Ты и хосты и урлы захочешь передавать из CI. Чем меньше опций переопределять, тем лучше.

2019-12-02 08:51 UTC, closed without merging